name: tests

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  RunTests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Testing
      run: cargo test -p core
