name: tests

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  RunTests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        c_compiler: [clang]
        include:
          - os: windows-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: make init

    - name: Build targets
      run: make build

    - name: Testing
      run: make test
